name: Run Azure CLI Login with OpenID Connect

on:
    push:
        branches: [ main ]

permissions:
  id-token: write
  contents: read
      
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name nkazureresumestorageweb --auth-mode key -d '$web' -s ./frontend --overwrite