name: New frontend worflow
on: 
  branch: [main]
    paths:
      - "frontend/**"

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check frontend directory
        run: |
          if [ ! -d "./frontend" ]; then
            echo "Frontend directory not found!"
            exit 1
          fi
          echo "Frontend directory exists, proceeding with deployment..."