name: Deploy Static Site to Azure Storage

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace API Key Placeholder
        run: |
          sed -i "s/API_KEY_PLACEHOLDER/${{ secrets.API_KEY }}/g" main.js

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --auth-mode login \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --destination '$web' \
              --source ./frontend \
              --overwrite